trigger:
  - master

pool:
  vmImage: 'macOS-10.14'

variables:
  - group: xamarin-full-pipeline
  - template: templates/variables.yml

schedules:
- cron: "0 0 * * 1-5"
  displayName: Daily midnight build
  branches:
    include:
    - master

stages:
  - stage: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Run Unit Tests'
        steps:
          - template: templates/run_unit_tests.yml
            parameters:
              solutionPath: '$(solutionPath)'
              projects: '$(Build.SourcesDirectory)/XamarinDevOps.Tests/*.csproj'
              buildConfiguration: '$(buildConfiguration)'

  - stage: Build_Xamarin_Android
    dependsOn: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Build Xamarin.Android'
        workspace:
          clean: all
        steps:
          - template: templates/init_restore.yml
            parameters:
              solutionPath: '$(solutionPath)'

          - template: templates/bump_android_manifest_version.yml
            parameters:
              androidManifestPath: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Properties/AndroidManifest.xml'

          - template: templates/icon_banner.yml
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Resources'
              contents: '**/icon.png'
              versionName: '$(buildConfiguration)'

          - template: templates/copy_content_file.yml
            parameters:
              sourceFile: '$(Build.SourcesDirectory)/configurations/config-$(buildConfiguration).json'
              targetFile: '$(Build.SourcesDirectory)/XamarinDevOps.Android/Assets/config.json'
          
          - template: templates/build_xamarin_android.yml
            parameters:
              xamarinSdkVersion: '$(xamarinSdkVersion)'
              packageFormat: 'aab' # Choose apk or aab depending on your needs
              projectFile: '$(Build.SourcesDirectory)/XamarinDevOps.Android/*.csproj'
              buildConfiguration: '$(buildConfiguration)'
              apksignerKeystoreFile: 'production.jks'
              apksignerKeystorePassword: $(keystore.password)
              apksignerKeystoreAlias: $(key.alias)
              apksignerKeyPassword: $(key.password)

  - stage: Build_Xamarin_iOS
    dependsOn: Run_Unit_Tests
    jobs:
      - job:
        displayName: 'Build Xamarin.iOS'
        workspace:
          clean: all
        steps:
          - template: templates/init_restore.yml
            parameters:
              solutionPath: '$(solutionPath)'

          - template: templates/bump_ios_version.yml
            parameters:
              infoPlistPath: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Info.plist'

          - template: templates/icon_banner.yml
            parameters:
              sourceFolder: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Assets.xcassets/AppIcon.appiconset'
              versionName: '$(buildConfiguration)'

          - template: templates/copy_content_file.yml
            parameters:
              sourceFile: '$(Build.SourcesDirectory)/configurations/config-$(buildConfiguration).json'
              targetFile: '$(Build.SourcesDirectory)/XamarinDevOps.iOS/Assets/config.json'

          - template: templates/build_xamarin_ios_ipa.yml
            parameters:
              xamarinSdkVersion: '$(xamarinSdkVersion)'
              p12FileName: '$(p12FileName)'
              p12Password: '$(p12Password)'
              provisioningProfile: '$(provisioningProfile)'
              solutionPath: '$(solutionPath)'
              buildConfiguration: '$(buildConfiguration)'
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'